spring:
  application:
    name: JB4DC-CLOUD-EUREKA-WEB-SERVER

server:
  port: 9101
  servlet:
    session:
      timeout: 7200

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: localhost
    #prefer-ip-address: true
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    #prefer-ip-address: true
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #serviceUrl:
    #defaultZone: http://192.168.3.153:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
