spring:
  application:
    name: JB4DC-CLOUD-CONFIG-WEB-SERVER
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
    inetutils:
      #客户端的IP
      preferred-networks: 192.168.3.153
  liquibase:
    enabled: false
  thymeleaf:
    prefix: classpath:/static/HTML/
    suffix: .html
    enabled: true

server:
  port: 9093
  servlet:
    session:
      timeout: 7200
    context-path: /JB4DCConfig

eureka:
  client:
    serviceUrl:
      #服务端的地址
      defaultZone: http://127.0.0.1:9092/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.cloud.inetutils.preferred-networks}:${server.port}